<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
	<ItemGroup>
		<Using Remove="System.Windows.Forms" />
		<Using Remove="System.Drawing" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>

</Project>
